### PR TITLE
Router rollback settings

### LINKED ISSUE #181: Allow reusing settings from a MockRouter instance on MockRouter.__call__
I'm wondering if it could be possible to support reusing _some_ settings of a `MockRouter` instance, when invoking `__call__`. Basically that'll allow me to specify a `MockRouter` with defaults, and for specific test cases flip the `assert_all_called`-flag.

Consider the code below. I want `base_url` and `assert_all_called` to have its default, unless they're overriden by a new `__call__` invocation

```python
import respx
default = respx.mock(base_url="http://some.where/", assert_all_called=False)
default.get(path="/here/")

with default(assert_all_called=True):
    httpx.get("http://some.where/here/")  # Raises: RESPX: <Request('GET', 'http://some.where/here/')> not mocked!

@default(assert_all_called=True)
def test_1():
    httpx.get("http://some.where/here/")  # Raises: RESPX: <Request('GET', 'http://some.where/here/')> not mocked!

test_1()

# This should still have the default `assert_all_called=False`
@default
def test_2():
    httpx.get("http://some.where/here/")  # This works

test_2()
```

Currently, this gives me an error whenever I pass in new kwargs to `default`(`test_1` and `with default`). As `__call__` is just creating a new `MockRouter` instance from scratch.

I'm realising as I write this that support for this might appear better through some additional `MockRouter` method (e.g. `MockRouter.replace()`) instead of changing `__call__`.

### PR DESCRIPTION
**Pull request by Mojken**
Adds router settings to the rollback functionality, as well as a function `configure()` which allows changing the settings of the router, creating a new snapshot.

Closes #181

### CODE REVIEW

**Comment by lundberg** [comment]
Thanks for the PR @Mojken. 

I also gave this a try but got stuck on the *bases*.

The intention of this requested configuration feature is for example to be able to change `base_url`, and in turn bases, for a router.

Changing the bases like you do will work, but only apply for new added routes, if any existing routes is present on the router when re-configuring the base_url, the existing routes will still have the old bases merged to their pattern.

**Comment by Mojken** [comment]
That sounds like expected behaviour to me. I wouldn't expect things I've set up before to be changed as a side-effect of me changing the configuration of the router. It doesn't seem like a very difficult thing to fix, perhaps adding a method to update old routes is a reasonable next step?

**Comment by flaeppe** [comment]
> I wouldn't expect things I've set up before to be changed as a side-effect of me changing the configuration of the router.

Actually I would. At least when standing on the outside looking in. Since it isn't really revealed that bases are merged together with routes to form and "freeze" a pattern.

e.g.

```python
import respx
mocker = respx.mock(base_url="http://localhost/")
mocker.get("some/path")
other_mocker = mocker(base_url="http://some.where/")
# After doing this, my initial assumption would be that 'other_mocker' is now capturing the following request
import httpx
with other_mocker:
    httpx.Client().get("http://some.where/some/path")
```

Just wanted to clarify what kind of behaviour I'm interested in, the snippet above should resemble my use case

**Comment by Farik1972** [comment]
> Adds router settings to the rollback functionality, as well as a function `configure()` which allows changing the settings of the router, creating a new snapshot.
> 
> Closes #181 

19f2e24c41a475a1b20e334c2064647203f3cd22

**Review by Farik1972 — APPROVED** [review]
- [ ]

**Review by paks000 — APPROVED** [review]

**Pull request closed without merging**
