### PR TITLE
Add support for Python 3.10

### PR DESCRIPTION
**Pull request by hugovk**
Python 3.10.0 final is due for release in October:

* https://www.python.org/dev/peps/pep-0619/

The first release candidate is now out and the Python release team has issued a call to action for community members:

> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.10 compatibilities during this phase. As always, report any issues to the Python bug tracker.

https://discuss.python.org/t/python-3-10-0rc1-is-now-available/9982?u=hugovk

So let's also test and add support for 3.10.

### CODE REVIEW

**Comment by lundberg** [comment]
Please add a simple test, probably in `test_router.py`, with a `Router` and no added routes, that should do the trick and get the branch coverage I think.

**Comment by hugovk** [comment]
I had a go but I wasn't quite sure what was needed to hit it, please could you have a look? Thanks!

**Comment by lundberg** [comment]
> I had a go but I wasn't quite sure what was needed to hit it, please could you have a look? Thanks!

@hugovk I added some missing type hints and tests in #165 that definitely covers the current "failing" coverage branch in this PR...even debugged it and stepped through those lines to make sure it followed that branch/path.

I think this is a bug in latest `coveragepy` + `3.10` 🤔.

Could you try adding/pinning `coveragepy` to the latest pre-release `6.0b1` in our `noxfile.py` and see if that solves it?

FYI, `coveragepy` is currently installed via `pytest-cov`, might be a problem with the pre-release, not sure.

**Comment by hugovk** [comment]
That worked! 👍

**Pull request merged**
