### PR TITLE
Add python 3.9 to test matrix

### PR DESCRIPTION
**Pull request by jairhenrique**

### CODE REVIEW

**Review by lundberg — COMMENTED** [review]
Awesome, thanks!

There are two minor coverage issues in the new `3.9` coverage report.

Please try to solve those, for 100% on all version, and we're good to merge.

**Comment by jairhenrique** [comment]
@lundberg I will try to debug it.

**Comment by lundberg** [comment]
> @lundberg I will try to debug it.

Great. Seams like the lines are covered, but not the *path to exit* for some reason in 3.9??

**Comment by jairhenrique** [comment]
@lundberg I think that's a coverage issue. I put a breakpoint before `raise` line and the tests pass many times there.

Screen Shot 2020-10-09 at 08 49 38

**Comment by lundberg** [comment]
> @lundberg I think that's a coverage issue. I put a breakpoint before `raise` line and the tests pass many times there.

Yep, I think you're right. I'll consider this OK.

**Pull request merged**
